### ISSUE TITLE
Just some tips

### ISSUE THREAD

**Issue by MaxGraey** [azu/consistent-hashing-wasm#1]
AssemblyScript have `i32` types with full featured integer arithmetic. `Math` namespace usually need only for `f64` and `Mathf` for `f32`.
1.
```ts
idx = <i32>Math.floor((lower + upper) / 2);
```
could be just:
```ts
idx = (lower + upper) / 2;
```
or better (also portable if you decide have uniform code for AS and JS):
```ts
idx = lower + ((upper - lower) >> 1); // eliminate overflowing when lower + upper >= 2 ** 32
```
2.
```ts
function compare(v1: i32, v2: i32): i32 {
    if (v1 > v2) {
        return 1;
    } else if (v1 < v2) {
        return -1
    }
    return v1 > v2 ? 1 : v1 < v2 ? -1 : 0;
}
```
just:
```ts
function compare(v1: i32, v2: i32): i32 {
  return v1 - v2;
}
```
3. `Math.pow` is pretty complex and expensive. Even for float point square numbers is better use for such simple case. But you have integers, so `Math.pow` completely unnecessary here:
```ts
let number = Math.pow(i, 2) as i32;
```
Much better:
```ts
let number = i * i
```

**Comment by azu** [comment]
Thanks!
